services:
  - type: web
    name: mysandingbridal
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildFilter:
      paths:
        - Dockerfile
        - .dockerignore
        - render.yaml
        - composer.json
        - package.json
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_URL
        value: https://mysandingbridal.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: db.ubamipcdottoorjzmnfd.supabase.co
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        value: clTfhLdlZAJ2nnAQ
      - key: FILESYSTEM_DISK
        value: cloudinary
      - key: CLOUDINARY_URL
        value: cloudinary://933245269893152:Op-kYoLJAz96h3aB9uRuWjpJbUo@dynonizve
      - key: SUPABASE_URL
        value: https://ubamipcdottoorjzmnfd.supabase.co
      - key: SUPABASE_API_KEY
        value: your_supabase_key
      - key: VITE_APP_URL
        value: https://mysandingbridal.onrender.com
